---
- include_tasks: create_tools_directory.yml
- include_tasks: install_chocolatey.yml
- include_tasks: install_packages.yml
- include_tasks: install_winget.yml
- include_tasks: install_winget_packages.yml
- include_tasks: install_visual_studio.yml
- include_tasks: install_roadrecon.yml
- include_tasks: install_roadtx.yml
- include_tasks: edit_path.yml
- include_tasks: debloat.yml
- include_tasks: todo.yml
