---
- name: Run Windows debloat script
  ansible.windows.win_shell: |
    & ([scriptblock]::Create((Invoke-RestMethod "https://debloat.raphi.re/"))) -RunDefaults -Silent
  become: yes
  become_method: runas
  become_user: SYSTEM
  register: debloat_result
  changed_when: true
  failed_when: debloat_result.rc != 0
