---
#- include_tasks: create_tools_directory.yml
#- include_tasks: install_chocolatey.yml
#- include_tasks: install_packages.yml
  # #- include_tasks: install_winget.yml
  # #- include_tasks: install_winget_packages.yml
  #- include_tasks: clone_git_repos.yml
  #- include_tasks: debloat.yml
- include_tasks: todo.yml
